#!/bin/bash

set -e

ELLIPTICS_VERSION=2.25.5.1
COCAINE_VERSION=0.11.2.5

IP=$(cat /etc/hosts | grep "${HOSTNAME}" | awk '{ print $1 }')

# add reverbrain repo
cat > /etc/apt/sources.list.d/reverbrain.list <<EOF
deb http://repo.reverbrain.com/precise/ current/amd64/
deb http://repo.reverbrain.com/precise/ current/all/
EOF

curl http://repo.reverbrain.com/REVERBRAIN.GPG | apt-key add -

# add docker repo
if [[ ! -e "/usr/lib/apt/methods/https" ]]; then
  apt-get install -y apt-transport-https
fi

apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 \
  --recv-keys 36A1D7869245C8950F966E92D8576A8BA88D21E9

cat > /etc/apt/sources.list.d/docker.list <<EOF
deb https://get.docker.io/ubuntu docker main
EOF

# install cocaine and docker
apt-get -y update
apt-get install -y cocaine-runtime="${COCAINE_VERSION}" \
  libcocaine-core2="${COCAINE_VERSION}" \
  libcocaine-plugin-docker2="${COCAINE_VERSION}" \
  libcocaine-plugin-elliptics="${ELLIPTICS_VERSION}" \
  elliptics-client="${ELLIPTICS_VERSION}" \
  lxc-docker
